services:
  docker:
    image: docker:dind
    privileged: true

pipeline:
  build:
    image: docker
    environment:
       - DOCKER_HOST=tcp://docker:2375
    commands:
       - docker build -t devbuild . 

  test:
    image: docker
    secrets: [ LICENCE ]
    environment:
       - DOCKER_HOST=tcp://docker:2375
    commands:
      - apk add --no-cache curl
      - docker run --name=DEV -d -p 8080:8080 -e "EXTRAS=+MinecraftModule.Java.MaxHeapSizeMB 256" -e "MODULE=Minecraft" -e LICENCE devbuild
      # Wait for AMP to install and start!
      - timeout -t 90 docker logs -f DEV &
      - sleep 30
      - curl -sSL --max-time 2 --retry 6 --retry-delay 10 docker:8080 > /dev/null
      - docker stop -t 30 DEV
      # Wait for it logging to exit
      - wait $(pidof timeout)

  publish:
    image: docker
    secrets: [ DOCKER_USER, DOCKER_PASS ]
    environment:
       - DOCKER_HOST=tcp://docker:2375
    commands:
       - docker tag devbuild adamant/amp
       - docker login -u $DOCKER_USER -p $DOCKER_PASS
       - docker push adamant/amp
       - echo "CONGRATS! SUCCESSFULLY BUILT AMP BASE IMAGE!"

  downstream:
    image: plugins/downstream
    secrets: [ DOWNSTREAM_TOKEN ]
    server: https://drone.adam-ant.co.uk
    fork: true
    repositories:
      - Adam-Ant/docker-ark-amp
    when:
      event:  [ push, tag, deployment ]
      status: [ success ]
